### ISSUE TITLE
Refactor to a request-based API

### ISSUE THREAD

**Issue by zlesnr** [newrelic/newrelic-cli#77] opened 2020-03-02 19:21 UTC
### Objective

As the needs of the APIs and API keys change over time, we'd like to be in a position where, for each API method, we would be able to select the "style" of API to use.  In some cases, even within a single package, we might want to implement GraphQL, while perhaps in a legacy method we might want to ensure we only ever use the V2 API.

### Acceptance Criteria
- The determination about which client pattern to use is easily surfaced when writing a new method.

**Comment by jthurman42** [comment] 2020-03-02 22:34
We should always prefer NerdGraph, and actively move away from everything in RESTv2 if it's available by some other means.

**Comment by ctrombley** [comment] 2020-03-09 17:44
Duplicate of newrelic/newrelic-client-go#156 .

**Closed by ctrombley** 2020-03-09 17:44 UTC
Labels: discussion, priority:medium, size:XL
