### ISSUE TITLE
Filtering returned attributes

### ISSUE THREAD

**Issue by zlesnr** [newrelic/newrelic-cli#88] opened 2020-03-02 19:43 UTC
### Objective
Provide a way for users to filter what fields are returned to the user without the user needing to use `jq`, for example.

### Acceptance Criteria
- The user can specify field names and only fields matching those names are returned in the object

**Comment by jthurman42** [comment] 2020-03-02 21:43
Related to newrelic/newrelic-client-go#159

**Comment by jthurman42** [comment] 2020-03-02 22:02
Duplicate of #44

**Closed by jthurman42** 2020-03-02 22:02 UTC
Labels: enhancement, size:M
