### ISSUE TITLE
Setting deployment marker fails with "invalid entity GUID format"

### ISSUE THREAD

**Issue by bbeesley** [newrelic/newrelic-cli#1606] opened 2024-05-14 14:42 UTC
### Description

We extensively use the [deployment marker action](https://github.com/newrelic/deployment-marker-action). It has worked perfectly for many months. Since [this PR](https://github.com/newrelic/newrelic-cli/pull/1605) was merged our calls to set the deployment marker now fail every time with a "invalid entity GUID format" error. The guid format isn't invalid, it's the same as its always been and it works fine with the previous version.

### Go Version
Unclear, it comes from [this docker image](https://hub.docker.com/r/newrelic/cli/tags).

### Current behavior
set deployment marker now fail every time with a "invalid entity GUID format" error.

### Expected behavior
set deployment marker properly sets a deployment marker

### Steps To Reproduce
Attempt to set a deployment marker using the github action, eg:

```
    - name: set newrelic application deployment marker
      uses: newrelic/deployment-marker-action@v2.2.0
      with:
        apiKey: NRAK-MYSECRETAPIKEY
        region: US
        guid: NDE2ODXXXXXXXXXXXXXXXXXXXXXXXXXXXX # obviously this should be an actual guid
        version: 69369ec22b883042b8f85d034900d469ae417656
        user: my-bot-user
        deploymenttype: BASIC
```

**Comment by atodd** [comment] 2024-05-14 19:51
I'm having the same issue.  Can we please have a fix or a recommended solution.

**Comment by GCamilleri** [comment] 2024-05-15 00:58
We are seeing exactly the same problem here. We use this feature in multiple pipelines many times daily. Seems like downgrading won't help as the code is in an underlying system. Following for a fix/workaround.

**Comment by NSSPKrishna** [comment] 2024-05-15 10:28
Hi all, I wanted to let you know that we've temporarily rolled back the recent change. Unfortunately, there isn't a straightforward workaround for this issue at the moment. To help us troubleshoot further, could you please verify that your entity GUID is correct by checking the metadata of the entity form the All Entities page or use this [link](https://api.newrelic.com/graphiql) to obtain it?

**Comment by NSSPKrishna** [comment] 2024-05-17 07:22
Hey everyone, I'm having trouble understanding the issue with the GUID decoding. Could you please share your GUID here so we can investigate further? Are there any specific error messages or logs that you're seeing? Any additional context you can provide would be super helpful in helping us troubleshoot this issue. Let's work together to get to the bottom of this!

**Comment by NSSPKrishna** [comment] 2024-05-21 18:03
👋  Hi again! @atodd @bbeesley @GCamilleri I wanted to follow up on the issue you reported. To help us better investigate and resolve the issue, could you please mail the entity GUIDs related to the issue to pniladhuri@newrelic.com? This will enable us to look into the matter further. Your help is greatly appreciated!

**Comment by bbeesley** [comment] 2024-05-22 09:12
It was every entity guid @NSSPKrishna . Every one of our deployment pipelines, and each environment within them. I can go and dig out the entity guid for every one of our APM services if you like but at that point it's probably easier to just give you our account id.

**Comment by NSSPKrishna** [comment] 2024-05-23 15:20
@bbeesley, thanks for reaching out to us about the issue you're experiencing. We've investigated the problem and are pleased to inform you that we've identified the root cause. We've also pushed a fix to our repository to resolve the issue. You can update your local copy by pulling the latest changes, and the issue should now be resolved. If you have any further questions or concerns, please don't hesitate to reach out.

**Closed** 2024-05-27 09:58 UTC
