### ISSUE TITLE
Fix errorValue race condition

### ISSUE THREAD

**Issue by zlesnr** [newrelic/newrelic-cli#75] opened 2020-03-02 19:17 UTC
### Description

Currently several portions of the code share an `errorValue` object for storing the error.  We should refactor away from this and fix the underlying issue to ensure that each portion of the code.

**Comment by ctrombley** [comment] 2020-03-02 21:10
Duplicate of newrelic/newrelic-client-go#161.  This issue was accidentally added to the wrong repo.

**Closed by ctrombley** 2020-03-02 21:10 UTC
